### ISSUE TITLE
BWASPR stuff should be removed from Singularity recipe. 

### ISSUE THREAD

**Issue by littleblackfish** [BrendelGroup/BWASP#45]
BWASPR stuff takes about 1/3 of the recipe, and as much of the build time. 

This part of the recipe requires the addition of 3rd party repositories (ppa:marutter..) and brings in R and Bioconductor dependencies which tend to evolve faster than the rest of BWASP. 

Maintaining these is a different animal than maintaining the rest of BWASP, and any issues in the build process will hinder the main BWASP container too. 

Similarly, Jupyter stuff necessary for my analysis is in a different independent container. 

I suggest that we move BWASPR stuff to its own recipe in its own repository, bump the new recipe to 1.0 and build/freeze it pretty soon.

**Comment by littleblackfish** [comment]
Fixed in 30d4718fde29186ad3b77cc2fb6682e03e3edcf9

**Comment by vpbrendel** [comment]
Done
