### ISSUE TITLE
get hsm positions using the output files of Bismark that i already have

### ISSUE THREAD

**Issue by AudryZhao** [BrendelGroup/BWASP#46]
hi Volker,

I‘m wondering whether there is a way to get hsm positions by using your scripts in bin folder with the output files of Bismark that i already have.
by the way, how do you define hsm positions and how do you get per gene methylation level?

thany you.

**Comment by vpbrendel** [comment]
1) Yes. "make -n" shows the dependencies in the workflow. You can start at any point or execute just parts of the workflow.
2) hsm are defined in the script CXreport2hsm.py. In words briefly in the Supporting Information to https://onlinelibrary.wiley.com/doi/full/10.1111/mec.13578.
3) Regional analyses can be done with the R scripts in our repository BWASPR. See also https://onlinelibrary.wiley.com/doi/full/10.1111/mec.15062
